### PR TITLE
Integrate llvm-project and bump dependencies

### PR DESCRIPTION
**Pull request by okkwon**
* llvm-project: 5ae0472694f5
* mlir-hlo: f6f29b1eb37e0601b1a06a3d3b0eb50c5c2b2b18
  * cherry-picked ea5b21f8f9cdd7cc97965a02d27967fe3c68cec1
* tensorflow: c8efbf27244b2a3ea4856654d52bd821ad3cf5a8

### CODE REVIEW

**Comment by okkwon** [comment]
There are several cmake changes in the upstream, which break the build. Looking into it.

**Comment by okkwon** [comment]
The cmake issue is fixed, but now I have errors with TF.
```
ERROR: /home/kbuilder/.cache/bazel/_bazel_kbuilder/1900d0fac5123d725c8d2e08b3f8c209/external/org_tensorflow/tensorflow/core/kernels/mkl/BUILD:280:22: Compiling tensorflow/core/kernels/mkl/mkl_dequantize_op.cc failed: (Exit 1): clang failed: error executing command /usr/lib/llvm-9/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 355 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/org_tensorflow/tensorflow/core/kernels/mkl/mkl_dequantize_op.cc:59:53: error: use 'template' keyword to treat 'flat' as a dependent template name
      const float min_range = ctx->input(kMinIndex).flat<float>()(0);
                                                    ^
                                                    template
external/org_tensorflow/tensorflow/core/kernels/mkl/mkl_dequantize_op.cc:60:53: error: use 'template' keyword to treat 'flat' as a dependent template name
      const float max_range = ctx->input(kMaxIndex).flat<float>()(0);
                                                    ^
                                                    template
2 errors generated.
```

**Comment by okkwon** [comment]
The code using only `flat` was introduced by https://github.com/milpuz01/tensorflow/commit/b601c0560402354bc3337cb51d94ca407102969c in May. I am not sure why the errors appear now.

**Comment by okkwon** [comment]
Okay, the code was made in May and pulled into tensorflow yesterday.

**Comment by okkwon** [comment]
This is the breaking PR. I asked the author to revert and fix it. 
https://github.com/tensorflow/tensorflow/pull/56086

**Comment by okkwon** [comment]
The issues with TF and mhlo were resolved in the upstreams. Abandoning this PR to handle them in a different PR with the latest changes.
