### ISSUE TITLE
can't build on Mac Sequoia 15.4

### ISSUE THREAD

**Issue by friendmine** [iree-org/iree#20472]
### What happened?

I'm currently compiling IREE on the macOS platform. 
However, following the  [official compilation instructions](https://iree.dev/building-from-source/getting-started/),  
as well as the content I get from my daily Git pull script, 
[build work flow script](https://github.com/iree-org/iree/actions/runs/14262207729/workflow)
neither allows me to complete the entire compilation process.
 I consistently encounter the following problem: 
**ld: symbol(s) not found for architecture arm64**

### Steps to reproduce your issue

the work flow script:

conda create -n iree python=3
conda activate iree
xcode-select --switch /Applications/Xcode.app/Contents/Developer
xcrun metal --version
xcrun metallib --version
pip install -r runtime/bindings/python/iree/runtime/build_requirements.txt
brew install ninja ccache coreutils bash
./build_tools/cmake/build_all.sh build-macos

got errors:
**ld: symbol(s) not found for architecture arm64**

**Comment by marbre** [comment]
We have only limited capacity to test on macOS and our workflow (`CI - macOS arm64 clang`) runs on macOS 14, thus issues with macOS 15 might indeed be uncovered. I can try to reproduce within the CI (macOS 15 seems to be in public preview on GH-hosted runners) but debugging might be difficult as I have access to a mac. Thus, help is appreciated.

**Comment by ScottTodd** [comment]
Can you share more context around the error message? Ideally full output from the `build_all.sh` script (or all CMake configure + build output).

**Comment by marbre** [comment]
I've triggered https://github.com/iree-org/iree/actions/runs/14317900035 that runs on `macos-15`.

**Comment by marbre** [comment]
> I've triggered https://github.com/iree-org/iree/actions/runs/14317900035 that runs on `macos-15`.

The workflow passed in the CI, thus I unfortunately cannot reproduce without further details.

**Comment by friendmine** [comment]
I've try to reolve it. maybe some env problems.

**Comment by marbre** [comment]
> I've try to reolve it. maybe some env problems.

Thanks. If you're still hitting the issue please provide further details.

**Comment by friendmine** [comment]
got some clues, it's okay to turn off GTEST now.
cmake -G Ninja -B ../iree-build/ . -DIREE_BUILD_TESTS=OFF
cmake --build ../iree-build/
can' build and run the source .

**Comment by benvanik** [comment]
perhaps gtest needs a bump
if you can provide an actual build log with cmake configure results and errors/warnings that would be useful

**Comment by friendmine** [comment]
[logout.txt](https://github.com/user-attachments/files/20405025/logout.txt) 

“The attachment contains the complete compilation output to the console.”
