### ISSUE TITLE
logical_right_shift 16bit compilation error on Vulkan

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#11828]
Reenable `tests/e2e/tosa_ops/logical_right_shift_16.mlir` on Vulkan.

(This testcase is introduced in #11826 . A CI run reproducing the current Spir-V error is expected in #11827).

**Comment by allieculp** [comment]
@antiagainst Is this still active?

**Comment by antiagainst** [comment]
i think so. I set it as P3 for now, given we won't get to it anytime soon.
