### ISSUE TITLE
macOS x64 clang build failing

### ISSUE THREAD

**Issue by marbre** [iree-org/iree#19591]
The `CI - macOS x64 clang` workflow started failing when scheduled for commit f1e1866 (build log https://github.com/iree-org/iree/actions/runs/12514308966) when linking `compiler/bindings/python/iree/compiler/_mlir_libs/_mlir.cpython-311-darwin.so`:

```
[7968/8273] Linking CXX shared module compiler/bindings/python/iree/compiler/_mlir_libs/_mlir.cpython-311-darwin.so
FAILED: compiler/bindings/python/iree/compiler/_mlir_libs/_mlir.cpython-311-darwin.so 
: && /Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=13.7 -bundle -Wl,-headerpad_max_install_names -Wl,@/Users/runner/work/iree/iree/build-macos/_deps/nanobind-src/cmake/darwin-ld-cpython.sym -lm -o compiler/bindings/python/iree/compiler/_mlir_libs/_mlir.cpython-311-darwin.so compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/MainModule.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRAffine.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRAttributes.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRCore.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRInterfaces.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRModule.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRTypes.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/Pass.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/Rewrite.cpp.o  -Wl,-rpath,@loader_path -Wl,-rpath,/Users/runner/work/iree/iree/build-macos/lib  llvm-project/lib/libnanobind-static.a  lib/libIREECompiler.dylib  llvm-project/lib/libLLVMSupport.a  -lm  llvm-project/lib/libLLVMDemangle.a && :
ld: warning: ignoring duplicate libraries: '-lm'
ld: Undefined symbols:
  _PyClassMethod_New, referenced from:
      mlir::python::populateIRCore(nanobind::module_&) in IRCore.cpp.o
      nanobind::object classmethod<nanobind::object (*)(nanobind::object const&, std::__1::optional<nanobind::list>, nanobind::list, std::__1::optional<nanobind::dict>, std::__1::optional<std::__1::vector<mlir::python::PyBlock*, std::__1::allocator<mlir::python::PyBlock*>>>, std::__1::optional<int>, mlir::python::DefaultingPyLocation, nanobind::object const&), nanobind::arg, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, char const*>(nanobind::object (*)(nanobind::object const&, std::__1::optional<nanobind::list>, nanobind::list, std::__1::optional<nanobind::dict>, std::__1::optional<std::__1::vector<mlir::python::PyBlock*, std::__1::allocator<mlir::python::PyBlock*>>>, std::__1::optional<int>, mlir::python::DefaultingPyLocation, nanobind::object const&), nanobind::arg, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, char const*) in IRCore.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The integrate commit f1e1866 updates LLVM to llvm/llvm-project@b135922. This includes llvm/llvm-project@b56d1ec with ports the Python core code to nanobind. The build only fails for macOS but passes for other platforms.

Till now, IREE's compiler bindings are build with pybind11. Porting IREE's compiler bindings from pybind11 to nanobind (PR #19580), the following (additional) targets fail for macOS which reference `_PyClassMethod_New`:
* `IREECompilerDialectsModule.cpp.o`
* `DialectGPU.cpp.o`
* `IRCore.cpp.o`
* `DialectPDL.cpp.o`
* `DialectLLVM.cpp.o`
* `DialectTransform.cpp.o`

Upstream macOS is several builds seem to pass, see for example https://github.com/makslevental/mlir-wheels/actions/runs/12565899455 or https://github.com/llvm/eudsl/actions/runs/12576273972/job/35052215749.

---
Errors (https://github.com/iree-org/iree/actions/runs/12583361482/job/35070746468) for PR #19580:  
```
[7969/8276] Linking CXX shared module compiler/bindings/python/iree/compiler/_mlir_libs/_ireeCompilerDialects.cpython-311-darwin.so
FAILED: compiler/bindings/python/iree/compiler/_mlir_libs/_ireeCompilerDialects.cpython-311-darwin.so 
: && /Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=13.7 -bundle -Wl,-headerpad_max_install_names -Wl,@/Users/runner/work/iree/iree/build-macos/_deps/nanobind-src/cmake/darwin-ld-cpython.sym -lm -o compiler/bindings/python/iree/compiler/_mlir_libs/_ireeCompilerDialects.cpython-311-darwin.so compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._ireeCompilerDialects.dso.dir/IREECompilerDialectsModule.cpp.o  -Wl,-rpath,@loader_path -Wl,-rpath,/Users/runner/work/iree/iree/build-macos/lib  llvm-project/lib/libnanobind-static.a  lib/libIREECompiler.dylib  llvm-project/lib/libLLVMSupport.a  -lm  llvm-project/lib/libLLVMDemangle.a && :
ld: warning: ignoring duplicate libraries: '-lm'
ld: Undefined symbols:
  _PyClassMethod_New, referenced from:
      nanobind_init__ireeCompilerDialects(nanobind::module_&) in IREECompilerDialectsModule.cpp.o
      nanobind_init__ireeCompilerDialects(nanobind::module_&) in IREECompilerDialectsModule.cpp.o
      nanobind_init__ireeCompilerDialects(nanobind::module_&) in IREECompilerDialectsModule.cpp.o
      nanobind_init__ireeCompilerDialects(nanobind::module_&) in IREECompilerDialectsModule.cpp.o
      nanobind_init__ireeCompilerDialects(nanobind::module_&) in IREECompilerDialectsModule.cpp.o
      nanobind_init__ireeCompilerDialects(nanobind::module_&) in IREECompilerDialectsModule.cpp.o
      nanobind_init__ireeCompilerDialects(nanobind::module_&) in IREECompilerDialectsModule.cpp.o
      nanobind_init__ireeCompilerDialects(nanobind::module_&) in IREECompilerDialectsModule.cpp.o
      ...
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```
[7971/8276] Linking CXX shared module compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsGPU.cpython-311-darwin.so
FAILED: compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsGPU.cpython-311-darwin.so 
: && /Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=13.7 -bundle -Wl,-headerpad_max_install_names -Wl,@/Users/runner/work/iree/iree/build-macos/_deps/nanobind-src/cmake/darwin-ld-cpython.sym -lm -o compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsGPU.cpython-311-darwin.so compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlirDialectsGPU.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/DialectGPU.cpp.o  -Wl,-rpath,@loader_path -Wl,-rpath,/Users/runner/work/iree/iree/build-macos/lib  llvm-project/lib/libnanobind-static.a  lib/libIREECompiler.dylib  llvm-project/lib/libLLVMSupport.a  -lm  llvm-project/lib/libLLVMDemangle.a && :
ld: warning: ignoring duplicate libraries: '-lm'
ld: Undefined symbols:
  _PyClassMethod_New, referenced from:
      _PyInit__mlirDialectsGPU in DialectGPU.cpp.o
      _PyInit__mlirDialectsGPU in DialectGPU.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```
[7973/8276] Linking CXX shared module compiler/bindings/python/iree/compiler/_mlir_libs/_mlir.cpython-311-darwin.so
FAILED: compiler/bindings/python/iree/compiler/_mlir_libs/_mlir.cpython-311-darwin.so 
: && /Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=13.7 -bundle -Wl,-headerpad_max_install_names -Wl,@/Users/runner/work/iree/iree/build-macos/_deps/nanobind-src/cmake/darwin-ld-cpython.sym -lm -o compiler/bindings/python/iree/compiler/_mlir_libs/_mlir.cpython-311-darwin.so compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/MainModule.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRAffine.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRAttributes.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRCore.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRInterfaces.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRModule.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/IRTypes.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/Pass.cpp.o compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlir.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/Rewrite.cpp.o  -Wl,-rpath,@loader_path -Wl,-rpath,/Users/runner/work/iree/iree/build-macos/lib  llvm-project/lib/libnanobind-static.a  lib/libIREECompiler.dylib  llvm-project/lib/libLLVMSupport.a  -lm  llvm-project/lib/libLLVMDemangle.a && :
ld: warning: ignoring duplicate libraries: '-lm'
ld: Undefined symbols:
  _PyClassMethod_New, referenced from:
      mlir::python::populateIRCore(nanobind::module_&) in IRCore.cpp.o
      nanobind::object classmethod<nanobind::object (*)(nanobind::object const&, std::__1::optional<nanobind::list>, nanobind::list, std::__1::optional<nanobind::dict>, std::__1::optional<std::__1::vector<mlir::python::PyBlock*, std::__1::allocator<mlir::python::PyBlock*>>>, std::__1::optional<int>, mlir::python::DefaultingPyLocation, nanobind::object const&), nanobind::arg, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, char const*>(nanobind::object (*)(nanobind::object const&, std::__1::optional<nanobind::list>, nanobind::list, std::__1::optional<nanobind::dict>, std::__1::optional<std::__1::vector<mlir::python::PyBlock*, std::__1::allocator<mlir::python::PyBlock*>>>, std::__1::optional<int>, mlir::python::DefaultingPyLocation, nanobind::object const&), nanobind::arg, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, nanobind::arg_v, char const*) in IRCore.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```
[7977/8276] Linking CXX shared module compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsLLVM.cpython-311-darwin.so
FAILED: compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsLLVM.cpython-311-darwin.so 
: && /Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=13.7 -bundle -Wl,-headerpad_max_install_names -Wl,@/Users/runner/work/iree/iree/build-macos/_deps/nanobind-src/cmake/darwin-ld-cpython.sym -lm -o compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsLLVM.cpython-311-darwin.so compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlirDialectsLLVM.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/DialectLLVM.cpp.o  -Wl,-rpath,@loader_path -Wl,-rpath,/Users/runner/work/iree/iree/build-macos/lib  llvm-project/lib/libnanobind-static.a  lib/libIREECompiler.dylib  llvm-project/lib/libLLVMSupport.a  -lm  llvm-project/lib/libLLVMDemangle.a && :
ld: warning: ignoring duplicate libraries: '-lm'
ld: Undefined symbols:
  _PyClassMethod_New, referenced from:
      populateDialectLLVMSubmodule(nanobind::module_ const&) in DialectLLVM.cpp.o
      populateDialectLLVMSubmodule(nanobind::module_ const&) in DialectLLVM.cpp.o
      populateDialectLLVMSubmodule(nanobind::module_ const&) in DialectLLVM.cpp.o
      populateDialectLLVMSubmodule(nanobind::module_ const&) in DialectLLVM.cpp.o
      populateDialectLLVMSubmodule(nanobind::module_ const&) in DialectLLVM.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```
[7980/8276] Linking CXX shared module compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsPDL.cpython-311-darwin.so
FAILED: compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsPDL.cpython-311-darwin.so 
: && /Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=13.7 -bundle -Wl,-headerpad_max_install_names -Wl,@/Users/runner/work/iree/iree/build-macos/_deps/nanobind-src/cmake/darwin-ld-cpython.sym -lm -o compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsPDL.cpython-311-darwin.so compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlirDialectsPDL.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/DialectPDL.cpp.o  -Wl,-rpath,@loader_path -Wl,-rpath,/Users/runner/work/iree/iree/build-macos/lib  llvm-project/lib/libnanobind-static.a  lib/libIREECompiler.dylib  llvm-project/lib/libLLVMSupport.a  -lm  llvm-project/lib/libLLVMDemangle.a && :
ld: warning: ignoring duplicate libraries: '-lm'
ld: Undefined symbols:
  _PyClassMethod_New, referenced from:
      populateDialectPDLSubmodule(nanobind::module_ const&) in DialectPDL.cpp.o
      populateDialectPDLSubmodule(nanobind::module_ const&) in DialectPDL.cpp.o
      populateDialectPDLSubmodule(nanobind::module_ const&) in DialectPDL.cpp.o
      populateDialectPDLSubmodule(nanobind::module_ const&) in DialectPDL.cpp.o
      populateDialectPDLSubmodule(nanobind::module_ const&) in DialectPDL.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```
[7983/8276] Linking CXX shared module compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsTransform.cpython-311-darwin.so
FAILED: compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsTransform.cpython-311-darwin.so 
: && /Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O2 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=13.7 -bundle -Wl,-headerpad_max_install_names -Wl,@/Users/runner/work/iree/iree/build-macos/_deps/nanobind-src/cmake/darwin-ld-cpython.sym -lm -o compiler/bindings/python/iree/compiler/_mlir_libs/_mlirDialectsTransform.cpython-311-darwin.so compiler/bindings/python/CMakeFiles/IREECompilerPythonModules.extension._mlirDialectsTransform.dso.dir/__/__/__/third_party/llvm-project/mlir/lib/Bindings/Python/DialectTransform.cpp.o  -Wl,-rpath,@loader_path -Wl,-rpath,/Users/runner/work/iree/iree/build-macos/lib  llvm-project/lib/libnanobind-static.a  lib/libIREECompiler.dylib  llvm-project/lib/libLLVMSupport.a  -lm  llvm-project/lib/libLLVMDemangle.a && :
ld: warning: ignoring duplicate libraries: '-lm'
ld: Undefined symbols:
  _PyClassMethod_New, referenced from:
      populateDialectTransformSubmodule(nanobind::module_ const&) in DialectTransform.cpp.o
      populateDialectTransformSubmodule(nanobind::module_ const&) in DialectTransform.cpp.o
      populateDialectTransformSubmodule(nanobind::module_ const&) in DialectTransform.cpp.o
      populateDialectTransformSubmodule(nanobind::module_ const&) in DialectTransform.cpp.o
      populateDialectTransformSubmodule(nanobind::module_ const&) in DialectTransform.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by marbre** [comment]
Dropping
https://github.com/iree-org/iree/blob/e6ac0161a7329aacdd829943469cafd4c3402159/CMakeLists.txt#L644
 does not resolve the problem. Furthermore,
https://github.com/iree-org/iree/blob/e6ac0161a7329aacdd829943469cafd4c3402159/build_tools/cmake/iree_llvm.cmake#L166
is already set if building with a bundled LLVM.

**Comment by makslevental** [comment]
I figured it out but I don't know what the right solution is yet; TL;DR we are in fact missing a symbol.

Upstream has these [`pure_subclass`](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Bindings/Python/NanobindAdaptors.h#L400) things which use `PyClassMethod_New` but `nanobind` doesn't and doesn't know about them in its [linker flags file](https://github.com/wjakob/nanobind/blob/b7c4f1abfcab9cc5a8f0ef758926d92ff5eac3a3/cmake/darwin-ld-cpython.sym). So a hack/patch fix (which works) is adding `-U PyClassMethod_New` to that nanobind file. 

The reason this doesn't fail upstream is because `HandleLLVMOptions` just [YOLOs all of the symbols on Mac](https://github.com/llvm/llvm-project/blob/1cbd67efe438bdf0a8183482471107363ce091d1/llvm/cmake/modules/HandleLLVMOptions.cmake#L254) (i.e. does `-undefined dynamic_lookup`) and somewhere IREE undoes that YOLO (no clue where).

There are couple of fixes:

1. fix in upstream to add `target_link_options(-U PyClassMethod_New)` to nanobind extensions;
2. change upstream to use the same cpython functions that nanobind uses (not sure which);
3. change IREE to YOLO just like upstream `HandleLLVMOptions`;
4. change IREE to do have the `-U PyClassMethod_New` linker flag.

I suppose it's 4 now to unblock and then 1 upstream.

cc @jpienaar @stellaraccident @yzhang93

**Comment by ScottTodd** [comment]
> The reason this doesn't fail upstream is because `HandleLLVMOptions` just [YOLOs all of the symbols on Mac](https://github.com/llvm/llvm-project/blob/1cbd67efe438bdf0a8183482471107363ce091d1/llvm/cmake/modules/HandleLLVMOptions.cmake#L254) (i.e. does `-undefined dynamic_lookup`) and somewhere IREE undoes that YOLO (no clue where).

IREE doesn't include `HandleLLVMOptions`. There's too much in there for a downstream with different usage models to unconditionally use in our experience. IREE has these files instead:

* https://github.com/iree-org/iree/blob/main/build_tools/cmake/iree_llvm.cmake
* https://github.com/iree-org/iree/blob/main/build_tools/cmake/iree_copts.cmake

**Comment by marbre** [comment]
> I suppose it's 4 now to unblock and then 1 upstream.

Thanks Maks! I would vote for 4 until we get possibly get option 1 or 2 later.

**Comment by stellaraccident** [comment]
Ugh. 4 is fine for now. Thanks for the triage

**Comment by stellaraccident** [comment]
I'm also fine with #3. It is pretty obnoxious when the build passes but all tests fail on a missing symbol, but whatever works. 

One thing that other projects do: use the nanobind stub generator as part of the build. That has the byproduct of loading the built library, causing linkage issues to be surfaced at build time. 

That's probably the most hands off was to do it that will require the least intervention over time.

**Comment by marbre** [comment]
Just cherry-picking and applying the fix on top of your current LLVM integrate (branch [iree-org/llvm-project: integrate/20250103+nanobind-fix](https://github.com/iree-org/llvm-project/tree/integrate/20250103%2Bnanobind-fix)) does not make the CI pass (Run [12630160413](https://github.com/iree-org/iree/actions/runs/12630160413)). Reverting the nanobind related upstream changes does (PR #19605, branch [iree-org/llvm-project: integrate/20250103+nanobind-reverts](https://github.com/iree-org/llvm-project/tree/integrate/20250103%2Bnanobind-teverts), Run [12621186146](https://github.com/iree-org/iree/actions/runs/12621186146)). Thus the upstream fix either relies on some intermediate patched which I missed to cherry-pick or this might need more work.

**Comment by makslevental** [comment]
Just a heads up (because I've been pulling my hair out for hours somewhere else about  this; `-Wl,-U` **is not correct for linux**:

`-DCMAKE_MODULE_LINKER_FLAGS="-Wl,-U -Wl,_PyClassMethod_New"`

and what will happen is you'll get the weirdest 

```
note: /usr/bin/ld: -r and -shared may not be used together
```

because the correct flag on linux is `-Wl,-u`. Quite infuriatingly the `u/U` flags mean basically opposite (or something) things on the two platforms:

Infuriatingly they mean the exact opposite things on the platforms:

# mac

## lld

```
-u symbol_name
             Specified that symbol symbol_name must be defined for the link to succeed.  
             This is useful to force selected functions to be loaded from a static library.

-U symbol_name
             Specified that it is ok for symbol_name to have no definition.  
             With -two_levelnamespace, the resulting symbol will be marked dynamic_lookup which means dyld will search all loaded images.
```

# linux 

## lld

```
  --undefined-glob=<pattern>
                          Force undefined symbol during linking
  --undefined-version     Allow unused version in version script (disabled by default)
  --undefined=<symbol>    Force undefined symbol during linking
  -u <value>              Alias for --undefined
```

## ld

```
  -Ur                         Build global constructor/destructor tables
  -u SYMBOL, --undefined SYMBOL
                              Start with undefined reference to SYMBOL
```

**Comment by marbre** [comment]
Build is unbroken with @makslevental patch, landing with PR #19796. This applies option 4 as option 1 alone isn't enough.
