### PR TITLE
Simplify tests/e2e/tosa_ops.

### LINKED ISSUE #11828: logical_right_shift 16bit compilation error on Vulkan
Reenable `tests/e2e/tosa_ops/logical_right_shift_16.mlir` on Vulkan.

(This testcase is introduced in #11826 . A CI run reproducing the current Spir-V error is expected in #11827).

### PR DESCRIPTION
**Pull request by ScottTodd**
Follow-up to https://github.com/iree-org/iree/pull/17843, forked from https://github.com/iree-org/iree/pull/17766

Fixes https://github.com/iree-org/iree/issues/11828

### CODE REVIEW

File: tests/e2e/stablehlo_ops/BUILD.bazel [hunk 1]
```diff
@@ -322,7 +322,7 @@ iree_check_single_backend_test_suite(
 )
 
 iree_check_single_backend_test_suite(
-    name = "check_meta-spirv_metal",
+    name = "check_metal-spirv_metal",
```
Comment (hanhanW) [inline tests/e2e/stablehlo_ops/BUILD.bazel:330]: good catch!

**Review by hanhanW — APPROVED** [review]

**Comment by ScottTodd** [comment]
Ah... I should probably have changes to `tests/` trigger the (now optional) GPU jobs automatically...

**Comment by ScottTodd** [comment]
Going to trust the older presubmit results 🤞
